"""Fetch the exercise photos the app shows, so users can see which equipment an exercise uses.

The photos come from free-exercise-db (public domain, Unlicense), pinned to one commit. Each strength
exercise gets its two photos (start and end position) as small WebP files in ``web/exercises/``, and
``src/exercise-photos.js`` lists their ids. Needs ffmpeg. Run: ``uv run python scripts/exercise_photos.py``
"""

import json
import subprocess
import tempfile
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

DATASET_COMMIT = "f00c92c7dcf1216a928a52c3706c7ce8e2f71ed5"
DATASET_URL = f"https://raw.githubusercontent.com/yuhonas/free-exercise-db/{DATASET_COMMIT}"
CATEGORIES = {"strength", "powerlifting", "olympic weightlifting", "strongman"}  # no stretches, cardio or jumps
PHOTO_WIDTH = 360  # px; the details sheet shows two side by side, thumbnails crop the middle
WEBP_QUALITY = 60

ROOT = Path(__file__).resolve().parent.parent
PHOTOS_DIR = ROOT / "web" / "exercises"
INDEX_FILE = ROOT / "src" / "exercise-photos.js"


def fetch(path: str) -> bytes:
    """One file from the pinned dataset."""
    with urllib.request.urlopen(f"{DATASET_URL}/{path}", timeout=60) as response:
        return response.read()


def save_photo(source: str, target: Path) -> None:
    """Download one photo and write it resized as WebP."""
    with tempfile.NamedTemporaryFile(suffix=".jpg") as original:
        original.write(fetch(f"exercises/{source}"))
        original.flush()
        subprocess.run(
            ["ffmpeg", "-loglevel", "error", "-y", "-i", original.name, "-vf", f"scale={PHOTO_WIDTH}:-2",
             "-c:v", "libwebp", "-quality", str(WEBP_QUALITY), str(target)],
            check=True,
        )


def main() -> None:
    exercises = [
        e for e in json.loads(fetch("dist/exercises.json"))
        if e["category"] in CATEGORIES and len(e["images"]) == 2
    ]
    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)
    jobs = [(image, PHOTOS_DIR / f"{e['id']}-{i}.webp") for e in exercises for i, image in enumerate(e["images"])]
    with ThreadPoolExecutor(max_workers=16) as pool:
        list(pool.map(lambda job: save_photo(*job), jobs))

    ids = sorted(e["id"] for e in exercises)
    INDEX_FILE.write_text(
        "// Generated by scripts/exercise_photos.py: exercises with photos in web/exercises/<id>-0.webp (start) and -1.webp (end).\n"
        f"// Source: free-exercise-db (public domain), commit {DATASET_COMMIT[:7]}.\n"
        f"export const EXERCISE_PHOTOS = {json.dumps(ids, indent=0)};\n"
    )
    print(f"{len(ids)} exercises, {len(jobs)} photos, {sum(p.stat().st_size for p in PHOTOS_DIR.iterdir()) // 1024} KB")


if __name__ == "__main__":
    main()
