// Reviewed photo matches for common exercise names (from Strong, Hevy and the coach), so they never need the AI.
// Names whose photo has the same name aren't listed. null: no photo fits. Matching ignores case and punctuation.
export const PHOTO_MATCHES = {
  "Bench Press": "Barbell_Bench_Press_-_Medium_Grip",
  "Incline Bench Press": "Barbell_Incline_Bench_Press_-_Medium_Grip",
  "Decline Bench Press": "Decline_Barbell_Bench_Press",
  "Close Grip Bench Press": "Close-Grip_Barbell_Bench_Press",
  "Incline Bench Press (Dumbbell)": "Incline_Dumbbell_Press",
  "Decline Bench Press (Dumbbell)": "Decline_Dumbbell_Bench_Press",
  "Chest Press (Machine)": "Machine_Bench_Press",
  "Incline Chest Press (Machine)": "Leverage_Incline_Chest_Press",
  "Chest Fly (Dumbbell)": "Dumbbell_Flyes",
  "Incline Chest Fly (Dumbbell)": "Incline_Dumbbell_Flyes",
  "Chest Fly (Machine)": "Butterfly",
  "Butterfly (Pec Deck)": "Butterfly",
  "Seated Chest Fly (Machine)": "Butterfly",
  "Chest Fly (Cable)": "Cable_Crossover",
  "Bench Fly (Dumbbell)": "Dumbbell_Flyes",
  "Push Up": "Pushups",
  "Dips": "Dips_-_Chest_Version",
  "Chest Dip": "Dips_-_Chest_Version",
  "Pullover (Dumbbell)": "Straight-Arm_Dumbbell_Pullover",
  "Dumbbell Pullover": "Straight-Arm_Dumbbell_Pullover",
  "Incline Press": "Barbell_Incline_Bench_Press_-_Medium_Grip",
  "Chest Fly": "Dumbbell_Flyes",
  "Deadlift": "Barbell_Deadlift",
  "Romanian Deadlift (Dumbbell)": "Stiff-Legged_Dumbbell_Deadlift",
  "Stiff Leg Deadlift": "Stiff-Legged_Barbell_Deadlift",
  "Deadlift (Dumbbell)": null,
  "Bent Over Row": "Bent_Over_Barbell_Row",
  "Bent Over Row (Dumbbell)": "Bent_Over_Two-Dumbbell_Row",
  "Barbell Row": "Bent_Over_Barbell_Row",
  "Pendlay Row": "Bent_Over_Barbell_Row",
  "Dumbbell Row": "One-Arm_Dumbbell_Row",
  "Bent Over One Arm Row (Dumbbell)": "One-Arm_Dumbbell_Row",
  "T Bar Row": "T-Bar_Row_with_Handle",
  "Seated Row (Cable)": "Seated_Cable_Rows",
  "Seated Cable Row": "Seated_Cable_Rows",
  "Seated Row (Machine)": "Leverage_Iso_Row",
  "Seated Row (Close Grip) (Machine)": "Leverage_Iso_Row",
  "Lat Pulldown": "Wide-Grip_Lat_Pulldown",
  "Lat Pulldown (Cable)": "Wide-Grip_Lat_Pulldown",
  "Lat Pulldown (Machine)": "Wide-Grip_Lat_Pulldown",
  "Lat Pulldown - Close Grip (Cable)": "Close-Grip_Front_Lat_Pulldown",
  "Pull Up": "Pullups",
  "Assisted Pull Up": "Band_Assisted_Pull-Up",
  "Pull Up (Assisted)": "Band_Assisted_Pull-Up",
  "Face Pull (Cable)": "Face_Pull",
  "Shrug": "Barbell_Shrug",
  "Back Extension": "Hyperextensions_Back_Extensions",
  "Hyperextension": "Hyperextensions_Back_Extensions",
  "Straight Arm Pulldown (Cable)": "Straight-Arm_Pulldown",
  "Squat": "Barbell_Squat",
  "Back Squat": "Barbell_Squat",
  "Barbell Back Squat": "Barbell_Squat",
  "Front Squat": "Front_Barbell_Squat",
  "Goblet Squat (Kettlebell)": "Goblet_Squat",
  "Goblet Squat (Dumbbell)": "Goblet_Squat",
  "Front Squat (Kettlebell)": "Front_Squats_With_Two_Kettlebells",
  "Sumo Squat (Dumbbell)": "Plie_Dumbbell_Squat",
  "Hack Squat (Machine)": "Hack_Squat",
  "Leg Press (Machine)": "Leg_Press",
  "Bulgarian Split Squat": "Split_Squat_with_Dumbbells",
  "Split Squat (Dumbbell)": "Split_Squat_with_Dumbbells",
  "Lunge": "Barbell_Lunge",
  "Lunge (Dumbbell)": "Dumbbell_Lunges",
  "Walking Lunge": "Bodyweight_Walking_Lunge",
  "Walking Lunge (Dumbbell)": "Dumbbell_Lunges",
  "Reverse Lunge": "Dumbbell_Rear_Lunge",
  "Step Up": "Barbell_Step_Ups",
  "Step Up (Dumbbell)": "Dumbbell_Step_Ups",
  "Leg Extension": "Leg_Extensions",
  "Leg Extension (Machine)": "Leg_Extensions",
  "Leg Curl": "Lying_Leg_Curls",
  "Lying Leg Curl (Machine)": "Lying_Leg_Curls",
  "Seated Leg Curl (Machine)": "Seated_Leg_Curl",
  "Hamstring Curl": "Lying_Leg_Curls",
  "Hip Thrust": "Barbell_Hip_Thrust",
  "Hip Thrust (Machine)": null,
  "Glute Bridge": "Butt_Lift_Bridge",
  "Glute Kickback (Cable)": "Glute_Kickback",
  "Hip Abductor (Machine)": "Thigh_Abductor",
  "Hip Adductor (Machine)": "Thigh_Adductor",
  "Seated Hip Abductor (Machine)": "Thigh_Abductor",
  "Seated Hip Adductor (Machine)": "Thigh_Adductor",
  "Calf Raise": "Standing_Calf_Raises",
  "Standing Calf Raise": "Standing_Calf_Raises",
  "Standing Calf Raise (Machine)": "Standing_Calf_Raises",
  "Seated Calf Raise (Machine)": "Seated_Calf_Raise",
  "Calf Press (Machine)": "Calf_Press_On_The_Leg_Press_Machine",
  "Kettlebell Swing": "One-Arm_Kettlebell_Swings",
  "Swing (Kettlebell)": "One-Arm_Kettlebell_Swings",
  "Zercher Squat": "Zercher_Squats",
  "Pistol Squat": "Kettlebell_Pistol_Squat",
  "Overhead Press": "Standing_Military_Press",
  "Shoulder Press": "Standing_Military_Press",
  "Military Press": "Standing_Military_Press",
  "Seated Overhead Press (Dumbbell)": "Seated_Dumbbell_Press",
  "Shoulder Press (Machine)": "Machine_Shoulder_Military_Press",
  "Arnold Press (Dumbbell)": "Arnold_Dumbbell_Press",
  "Arnold Press": "Arnold_Dumbbell_Press",
  "Lateral Raise": "Side_Lateral_Raise",
  "Lateral Raise (Dumbbell)": "Side_Lateral_Raise",
  "Lateral Raise (Cable)": "Standing_Low-Pulley_Deltoid_Raise",
  "Lateral Raise (Machine)": null,
  "Front Raise (Dumbbell)": "Front_Dumbbell_Raise",
  "Reverse Fly (Dumbbell)": "Reverse_Flyes",
  "Rear Delt Fly (Dumbbell)": "Reverse_Flyes",
  "Reverse Fly (Machine)": "Reverse_Machine_Flyes",
  "Upright Row": "Upright_Barbell_Row",
  "Bicep Curl": "Barbell_Curl",
  "Bicep Curl (Cable)": "Standing_Biceps_Cable_Curl",
  "Dumbbell Curl": "Dumbbell_Bicep_Curl",
  "Hammer Curl": "Hammer_Curls",
  "Hammer Curl (Dumbbell)": "Hammer_Curls",
  "Hammer Curl (Cable)": "Cable_Hammer_Curls_-_Rope_Attachment",
  "Incline Curl (Dumbbell)": "Incline_Dumbbell_Curl",
  "Incline Bicep Curl (Dumbbell)": "Incline_Dumbbell_Curl",
  "Preacher Curl (Dumbbell)": "Two-Arm_Dumbbell_Preacher_Curl",
  "Preacher Curl (Machine)": "Machine_Preacher_Curls",
  "Concentration Curl": "Concentration_Curls",
  "Reverse Curl": "Reverse_Barbell_Curl",
  "Wrist Curl": "Palms-Up_Barbell_Wrist_Curl_Over_A_Bench",
  "Triceps Pushdown (Cable)": "Triceps_Pushdown",
  "Triceps Rope Pushdown": "Triceps_Pushdown_-_Rope_Attachment",
  "Skull Crusher": "EZ-Bar_Skullcrusher",
  "Triceps Extension (Dumbbell)": "Standing_Dumbbell_Triceps_Extension",
  "Overhead Triceps Extension (Cable)": "Cable_Rope_Overhead_Triceps_Extension",
  "Triceps Dip": "Dips_-_Triceps_Version",
  "Bench Dip": "Bench_Dips",
  "Crunch": "Crunches",
  "Crunch (Machine)": "Ab_Crunch_Machine",
  "Leg Raise": "Flat_Bench_Lying_Leg_Raise",
  "Ab Wheel": "Ab_Roller",
  "Ab Rollout": "Ab_Roller",
  "Side Plank": "Side_Bridge",
  "Mountain Climber": null,
  "Bicycle Crunch": "Cross-Body_Crunch",
  "Thruster": "Kettlebell_Thruster",
  "Turkish Get Up": "Kettlebell_Turkish_Get-Up_Squat_style",
  "Cable Row": "Seated_Cable_Rows",
  "Hip Thrust (Dumbbell)": "Barbell_Hip_Thrust",
  "Single Leg Romanian Deadlift (Dumbbell)": "Kettlebell_One-Legged_Deadlift",
  "Kettlebell Deadlift": null,
  "Kettlebell Goblet Squat": "Goblet_Squat",
  "Renegade Row (Dumbbell)": "Alternating_Renegade_Row",
};
